name: Release Build
on:
  release:
    types: [created]
env:
  CARGO_TERM_COLOR: always
  
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build -r
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          filename: 'xiso-ex-linux.zip'
          path: target/release/xiso-ex
          custom: -j
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: "xiso-ex-linux.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build -r
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          filename: 'xiso-ex-macos.zip'
          path: target/release/xiso-ex
          custom: -j
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: "xiso-ex-macos.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build -r
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          filename: 'xiso-ex-windows.zip'
          path: "%CD%/target/release/xiso-ex.exe"
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: "xiso-ex-windows.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
