name: Release Build
on:
  release:
    types: [created]
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_and_release:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --verbose -r
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          filename: "xiso-ex-${{ matrix.os }}.zip"
          path: target/release/xiso-ex
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "xiso-ex-${{ matrix.os }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
